import { TheHeader } from "@/componets/TheHeader";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TheFooter } from "@/componets/TheFooter";
import { Provider } from "@/componets/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider>
				<TheHeader />
				<main>{children}</main>
				<TheFooter />
				</Provider>
			</body>
		</html>
	);
}
